name: secret_santa
description: "MTG Secret Santa 20 24"
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  flutter_gradient_animation_text: ^1.0.2
  url_launcher: ^6.3.0
  video_player: ^2.9.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/videos/
  fonts:
    - family: Creepster
      fonts:
        - asset: assets/fonts/Creepster-Regular.ttf
    - family: Nabla
      fonts:
        - asset: assets/fonts/Nabla-Regular.ttf
